// @generated by scripts/codegen.mjs from packages/web/drizzle/schema.sql.
// DO NOT EDIT. Run `npm run db:codegen` after changing schema.sql.

import { pgTable, uuid, text, timestamp, index, foreignKey, check, jsonb, integer, bigint, primaryKey } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const askers = pgTable("askers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	displayName: text("display_name").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const questions = pgTable("questions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	askerId: uuid("asker_id"),
	text: text().notNull(),
	topic: text(),
	nonce: text().default(sql`encode(gen_random_bytes(16), 'base64')`).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
	closesAt: timestamp("closes_at", { withTimezone: true }).notNull(),
	status: text().default('open').notNull(),
	options: jsonb().$type<string[]>().default(["yes","no"]).notNull(),
	scope: text().default('worldwide').notNull(),
	country: text(),
	continent: text(),
}, (table) => {
	return {
		continentIdx: index("questions_continent_idx").using("btree", table.continent.asc().nullsLast().op("text_ops")),
		countryIdx: index("questions_country_idx").using("btree", table.country.asc().nullsLast().op("text_ops")),
		scopeIdx: index("questions_scope_idx").using("btree", table.scope.asc().nullsLast().op("text_ops")),
		questionsAskerIdFkey: foreignKey({
			columns: [table.askerId],
			foreignColumns: [askers.id],
			name: "questions_asker_id_fkey"
		}),
		questionsStatusChk: check("questions_status_chk", sql`status = ANY (ARRAY['open'::text, 'closed'::text])`),
		questionsScopeChk: check("questions_scope_chk", sql`scope = ANY (ARRAY['worldwide'::text, 'continent'::text, 'country'::text])`),
		questionsOptionsChk: check("questions_options_chk", sql`(jsonb_typeof(options) = 'array'::text) AND ((jsonb_array_length(options) >= 2) AND (jsonb_array_length(options) <= 8))`),
		questionsContinentChk: check("questions_continent_chk", sql`(continent IS NULL) OR (continent = ANY (ARRAY['AF'::text, 'AN'::text, 'AS'::text, 'EU'::text, 'NA'::text, 'OC'::text, 'SA'::text]))`),
		questionsScopeGeoChk: check("questions_scope_geo_chk", sql`((scope = 'worldwide'::text) AND (country IS NULL) AND (continent IS NULL)) OR ((scope = 'continent'::text) AND (country IS NULL) AND (continent IS NOT NULL)) OR ((scope = 'country'::text) AND (country IS NOT NULL) AND (continent IS NOT NULL))`),
	}
});

export const aggregates = pgTable("aggregates", {
	questionId: uuid("question_id").primaryKey().notNull(),
	totalAnswers: integer("total_answers").default(0).notNull(),
	byPredicate: jsonb("by_predicate").default({}).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => {
	return {
		aggregatesQuestionIdFkey: foreignKey({
			columns: [table.questionId],
			foreignColumns: [questions.id],
			name: "aggregates_question_id_fkey"
		}),
	}
});

export const revocations = pgTable("revocations", {
	delegationHash: text("delegation_hash").primaryKey().notNull(),
	revokedAt: timestamp("revoked_at", { withTimezone: true }).defaultNow().notNull(),
});

export const registrations = pgTable("registrations", {
	uniqueIdentifier: text("unique_identifier").primaryKey().notNull(),
	agentKey: text("agent_key").notNull(),
	disclosedPredicates: jsonb("disclosed_predicates").notNull(),
	issuedAt: timestamp("issued_at", { withTimezone: true }).defaultNow().notNull(),
	expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
	revokedAt: timestamp("revoked_at", { withTimezone: true }),
}, (table) => {
	return {
		agentKeyIdx: index("registrations_agent_key_idx").using("btree", table.agentKey.asc().nullsLast().op("text_ops")),
	}
});

export const selfNullifierInvalidations = pgTable("self_nullifier_invalidations", {
	uniqueIdentifier: text("unique_identifier").primaryKey().notNull(),
	source: text().notNull(),
	chainId: text("chain_id"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	blockNumber: bigint("block_number", { mode: "number" }).notNull(),
	logIndex: integer("log_index").notNull(),
	txHash: text("tx_hash").notNull(),
	observedAt: timestamp("observed_at", { withTimezone: true }).defaultNow().notNull(),
});

export const selfChainCursors = pgTable("self_chain_cursors", {
	name: text().primaryKey().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	lastBlock: bigint("last_block", { mode: "number" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const envelopes = pgTable("envelopes", {
	questionId: uuid("question_id").notNull(),
	uniqueIdentifier: text("unique_identifier").notNull(),
	answer: text().notNull(),
	disclosedPredicates: jsonb("disclosed_predicates").notNull(),
	agentSignature: text("agent_signature").notNull(),
	delegationHash: text("delegation_hash").notNull(),
	submittedAt: timestamp("submitted_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => {
	return {
		questionIdIdx: index("envelopes_question_id_idx").using("btree", table.questionId.asc().nullsLast().op("uuid_ops")),
		submittedAtIdx: index("envelopes_submitted_at_idx").using("btree", table.submittedAt.asc().nullsLast().op("timestamptz_ops")),
		envelopesQuestionIdFkey: foreignKey({
			columns: [table.questionId],
			foreignColumns: [questions.id],
			name: "envelopes_question_id_fkey"
		}),
		envelopesPkey: primaryKey({ columns: [table.questionId, table.uniqueIdentifier], name: "envelopes_pkey"}),
	}
});
