//! Hermes host adapter — directory plugin install + subprocess shim.
//!
//! Hermes' built-in installers don't fit our shape, so we use the deterministic
//! path: drop a 2-file directory under `~/.hermes/plugins/chorum/` (manifest +
//! a stdlib-only Python shim that shells out to this binary), then restart the
//! gateway. Because the gateway runs Python but has no `chorum_skill` package
//! installed (binary mode), the shim re-implements the two-tool contract by
//! invoking the binary's CLI subcommands.

use std::path::{Path, PathBuf};
use std::process::Command;

use crate::contracts::{
    answer_toolsets_py, py_str, ANSWER_PROMPT, BUDGET_SUSPEND_SCHEDULE, DEFAULT_SCHEDULE, JOB_NAME,
    LIST_SCHEMA_PY, SUBMIT_NO_SIGNAL_SCHEMA_PY, SUBMIT_SCHEMA_PY, TOOLSET,
};
use crate::Error;

const PLUGIN_DIRNAME: &str = "chorum";

/// Embedded Hermes manifest. Kept in step with packages/skill/plugin.yaml.
pub const PLUGIN_MANIFEST: &str = "name: chorum\nversion: 0.0.1\ndescription: >-\n  Answer public yes/no questions on the user's behalf, using the host agent's\n  own model and memory. Inference needs no extra API key; a cron job drives the\n  answering cycle.\nauthor: Chorum\nkind: standalone\nprovides_tools:\n  - chorum_list_open_questions\n  - chorum_submit_answer\n  - chorum_submit_no_signal\n";

/// The default Hermes root (`~/.hermes`), ignoring `$HERMES_HOME`. Named
/// profiles always live under `<this>/profiles/<name>`, regardless of which
/// home is currently active.
pub fn default_hermes_root() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".hermes")
}

/// The *active* Hermes home. Honors `$HERMES_HOME` (set by Hermes itself for a
/// named profile, by its per-profile wrapper alias, or by our own
/// `--hermes-profile`/`--hermes-home` flags), falling back to `~/.hermes`.
/// Every install path is derived from this so the plugin lands in the same
/// profile the gateway runs under.
pub fn hermes_home() -> PathBuf {
    std::env::var_os("HERMES_HOME")
        .filter(|v| !v.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(default_hermes_root)
}

/// Names of the profiles present under `~/.hermes/profiles`, sorted. Empty if
/// there are none (the common single-profile case).
pub fn list_profiles() -> Vec<String> {
    profiles_in(&default_hermes_root())
}

fn profiles_in(root: &Path) -> Vec<String> {
    let mut out = Vec::new();
    if let Ok(entries) = std::fs::read_dir(root.join("profiles")) {
        for entry in entries.flatten() {
            if entry.path().is_dir() {
                if let Some(name) = entry.file_name().to_str() {
                    out.push(name.to_string());
                }
            }
        }
    }
    out.sort();
    out
}

pub fn plugin_dir() -> PathBuf {
    hermes_home().join("plugins").join(PLUGIN_DIRNAME)
}

pub fn hermes_env_path() -> PathBuf {
    hermes_home().join(".env")
}

/// The active profile's Hermes `config.yaml` (honors `$HERMES_HOME`, same as
/// Hermes' own `get_config_path()`). This is where the plugin allow-list lives.
pub fn config_path() -> PathBuf {
    hermes_home().join("config.yaml")
}

/// Build the self-contained Hermes plugin shim that shells out to `binary_path`.
/// The source imports only the stdlib (the `cron` import is lazy), so it loads
/// inside a gateway with no `chorum_skill` package.
///
/// `chorum_root` is the data root (`<profile-home>/chorum`) this shim is being
/// installed into. When present it is baked in and passed to every binary
/// invocation as `CHORUM_SKILL_ROOT_DIR`, so the answering subprocess always
/// reads the delegation token, policy, and ledger of the profile it was
/// installed under — even when a cron/sandbox subprocess does not inherit
/// `HERMES_HOME`. Pass `None` only when the install target is off the standard
/// `<home>/plugins/chorum` layout, in which case the shim falls back to the
/// runtime `CHORUM_SKILL_ROOT_DIR`/`HERMES_HOME` resolution.
pub fn build_subprocess_shim(binary_path: &str, chorum_root: Option<&str>) -> String {
    const TEMPLATE: &str = r##""""Auto-generated Chorum plugin shim (binary mode).

Generated by `chorum-skill install` / `install-plugin` running as the
standalone `chorum-skill` binary. The Hermes gateway loads this module; it
needs NO pip-installed chorum_skill package — every operation shells out to
the binary below. Do not edit by hand; re-run the installer to regenerate.
"""

import json
import logging
import os
import subprocess
from pathlib import Path

log = logging.getLogger("chorum_skill.shim")

CHORUM_BIN = @@CHORUM_BIN@@
# The profile data root (`<profile-home>/chorum`) this shim was installed into,
# baked in at install time. Empty string means "resolve at runtime" (legacy /
# off-standard-layout installs).
CHORUM_ROOT = @@CHORUM_ROOT@@
TOOLSET = @@TOOLSET@@
# Toolsets granted to the answering cron: chorum's submit tools PLUS the agent's
# own recall tools (session_search over past conversations, memory for
# MEMORY.md/USER.md), so it can look the user up before answering instead of
# running blind.
ANSWER_TOOLSETS = @@ANSWER_TOOLSETS@@
JOB_NAME = @@JOB_NAME@@
DEFAULT_SCHEDULE = @@DEFAULT_SCHEDULE@@
# Cadence the cron is parked on once the monthly budget is reached (09:00 on the
# 1st). It stays scheduled but won't fire until the new month, when the budget
# resets and the first run swaps it back to DEFAULT_SCHEDULE.
BUDGET_SUSPEND_SCHEDULE = @@BUDGET_SUSPEND_SCHEDULE@@
ANSWER_PROMPT = @@ANSWER_PROMPT@@
_LIST_SCHEMA = @@LIST_SCHEMA@@
_SUBMIT_SCHEMA = @@SUBMIT_SCHEMA@@
_SUBMIT_NO_SIGNAL_SCHEMA = @@SUBMIT_NO_SIGNAL_SCHEMA@@


def _skill_env():
    # Pin the binary's data root to the profile this plugin was installed into.
    # The gateway is profile-aware in-process, but a cron/sandbox subprocess does
    # not reliably inherit HERMES_HOME — without this the binary would silently
    # fall back to the global ~/.hermes/chorum (wrong delegation token + ledger).
    # An explicit CHORUM_SKILL_ROOT_DIR already in the environment wins, so an
    # operator can still override.
    env = os.environ.copy()
    if CHORUM_ROOT and not env.get("CHORUM_SKILL_ROOT_DIR"):
        env["CHORUM_SKILL_ROOT_DIR"] = CHORUM_ROOT
    return env


def _run(args):
    try:
        proc = subprocess.run(
            [CHORUM_BIN, *args],
            capture_output=True,
            text=True,
            timeout=180,
            env=_skill_env(),
        )
    except Exception as exc:  # noqa: BLE001
        return json.dumps({"error": "chorum binary failed: " + str(exc)})
    out = (proc.stdout or "").strip()
    if out:
        return out
    return json.dumps({"error": (proc.stderr or "no output from chorum binary").strip()})


def _handle_list(args, **_kwargs):
    out = _run(["list-questions"])
    _apply_budget_schedule(out)
    return out


def _apply_budget_schedule(raw):
    # Cost backstop: when the binary reports the monthly budget is reached
    # (budget_reached=true), park the cron on BUDGET_SUSPEND_SCHEDULE so it
    # stops firing — and stops incurring host-model cost — until the budget
    # resets next month. On the first run of the new month the binary is back
    # under budget, so we swap the daily cadence back in. Changing the SCHEDULE
    # (not next_run_at) is deliberate: Hermes' post-run mark_job_run recomputes
    # next_run_at from the schedule, so a one-off next_run_at would be undone.
    # Strictly best-effort — any failure leaves the schedule untouched and the
    # binary's empty result already prevents (paid) answering this cycle.
    try:
        data = json.loads(raw)
    except Exception:
        return
    if not isinstance(data, dict):
        return
    try:
        from cron.jobs import resolve_job_ref, update_job
    except Exception:
        return  # not inside the gateway / cron API unavailable
    try:
        job = resolve_job_ref(JOB_NAME)
        if not job:
            return
        current = (job.get("schedule") or {}).get("expr")
        if data.get("budget_reached"):
            if current != BUDGET_SUSPEND_SCHEDULE:
                update_job(job["id"], {"schedule": BUDGET_SUSPEND_SCHEDULE})
                log.info("chorum: monthly budget reached — cron parked until next month")
        elif current == BUDGET_SUSPEND_SCHEDULE:
            # New month, back under budget → restore the normal daily cadence.
            update_job(job["id"], {"schedule": DEFAULT_SCHEDULE})
            log.info("chorum: budget reset — cron restored to daily (%s)", DEFAULT_SCHEDULE)
    except Exception:
        log.debug("chorum budget reschedule skipped", exc_info=True)


def _handle_submit(args, **_kwargs):
    a = args or {}
    question_id = str(a.get("question_id") or "").strip()
    answer = str(a.get("answer") or "").strip()
    if not question_id or not answer:
        return json.dumps({"accepted": False, "reason": "question_id and answer are required"})
    return _run(["submit-answer", "--question-id", question_id, "--answer", answer])


def _handle_submit_no_signal(args, **_kwargs):
    a = args or {}
    question_id = str(a.get("question_id") or "").strip()
    if not question_id:
        return json.dumps({"accepted": False, "reason": "question_id is required"})
    return _run(["submit-no-signal", "--question-id", question_id])


def _chorum_root():
    # Mirror the binary's config::default_root resolution so the shim (running
    # inside the gateway) looks in the SAME profile the gateway runs under. An
    # explicit env override wins; then the install-time baked root; then the
    # runtime HERMES_HOME fallback.
    explicit = os.environ.get("CHORUM_SKILL_ROOT_DIR")
    if explicit:
        return Path(explicit)
    if CHORUM_ROOT:
        return Path(CHORUM_ROOT)
    hermes_home = os.environ.get("HERMES_HOME")
    base = Path(hermes_home) if hermes_home else (Path.home() / ".hermes")
    return base / "chorum"


def _delegation_exists():
    return (_chorum_root() / "delegation.token").exists()


def _ensure_cron():
    # The shim runs inside the Hermes gateway, so the `cron` package is importable here.
    if not _delegation_exists():
        return
    try:
        from cron.jobs import create_job, resolve_job_ref
    except Exception:  # noqa: BLE001
        return
    try:
        if resolve_job_ref(JOB_NAME):
            return
        create_job(
            prompt=ANSWER_PROMPT,
            schedule=DEFAULT_SCHEDULE,
            name=JOB_NAME,
            enabled_toolsets=list(ANSWER_TOOLSETS),
        )
    except Exception:  # noqa: BLE001
        log.debug("Chorum cron auto-registration skipped", exc_info=True)


def register(ctx):
    ctx.register_tool(
        name="chorum_list_open_questions",
        toolset=TOOLSET,
        schema=_LIST_SCHEMA,
        handler=_handle_list,
        description="List open Chorum questions the policy permits answering.",
        emoji="\U0001f5f3️",
    )
    ctx.register_tool(
        name="chorum_submit_answer",
        toolset=TOOLSET,
        schema=_SUBMIT_SCHEMA,
        handler=_handle_submit,
        description="Sign + submit one Chorum answer on the user's behalf.",
        emoji="\U0001f5f3️",
    )
    ctx.register_tool(
        name="chorum_submit_no_signal",
        toolset=TOOLSET,
        schema=_SUBMIT_NO_SIGNAL_SCHEMA,
        handler=_handle_submit_no_signal,
        description="Record that the user has no formed view on one Chorum question.",
        emoji="\U0001f5f3️",
    )
    _ensure_cron()
"##;

    TEMPLATE
        .replace("@@CHORUM_BIN@@", &py_str(binary_path))
        .replace("@@CHORUM_ROOT@@", &py_str(chorum_root.unwrap_or("")))
        .replace("@@TOOLSET@@", &py_str(TOOLSET))
        .replace("@@ANSWER_TOOLSETS@@", &answer_toolsets_py())
        .replace("@@JOB_NAME@@", &py_str(JOB_NAME))
        .replace("@@DEFAULT_SCHEDULE@@", &py_str(DEFAULT_SCHEDULE))
        .replace(
            "@@BUDGET_SUSPEND_SCHEDULE@@",
            &py_str(BUDGET_SUSPEND_SCHEDULE),
        )
        .replace("@@ANSWER_PROMPT@@", &py_str(ANSWER_PROMPT))
        .replace("@@LIST_SCHEMA@@", LIST_SCHEMA_PY)
        .replace("@@SUBMIT_NO_SIGNAL_SCHEMA@@", SUBMIT_NO_SIGNAL_SCHEMA_PY)
        .replace("@@SUBMIT_SCHEMA@@", SUBMIT_SCHEMA_PY)
}

/// Write the Hermes directory-install drop-in (manifest + shim). Idempotent;
/// always overwrites both files. `binary_path` defaults to the current
/// executable. Returns the directory written.
pub fn install_plugin_dir(
    plugin_dir_override: Option<&Path>,
    binary_path: Option<&str>,
) -> Result<PathBuf, Error> {
    let target = plugin_dir_override
        .map(|p| p.to_path_buf())
        .unwrap_or_else(plugin_dir);
    std::fs::create_dir_all(&target)?;
    std::fs::write(target.join("plugin.yaml"), PLUGIN_MANIFEST)?;

    let resolved_bin = match binary_path {
        Some(b) => b.to_string(),
        None => std::env::current_exe()?.to_string_lossy().into_owned(),
    };
    // Pin the shim to the profile it lives in: target is `<home>/plugins/chorum`,
    // so its grandparent is the Hermes home and `<home>/chorum` is the data root.
    // Off-standard layouts (no two parents) bake nothing and fall back to the
    // shim's runtime resolution.
    let chorum_root = target
        .parent()
        .and_then(|plugins| plugins.parent())
        .map(|home| home.join("chorum").to_string_lossy().into_owned());
    std::fs::write(
        target.join("__init__.py"),
        build_subprocess_shim(&resolved_bin, chorum_root.as_deref()),
    )?;
    Ok(target)
}

/// Add `chorum` to the plugin allow-list in Hermes' `config.yaml`.
///
/// Hermes loads `standalone` plugins opt-in: a plugin only loads if its name is
/// in `plugins.enabled`. Dropping the plugin dir is not enough — on a fresh
/// (named) profile the gateway discovers the drop-in but skips it, so the
/// shim's `register()` (and with it the cron self-registration) never runs.
/// Mirror `hermes plugins enable chorum`: add `chorum` to `plugins.enabled`
/// (sorted + deduped, matching Hermes' `sorted(set(...))` write) and drop it
/// from `plugins.disabled`, preserving every other key. The default profile
/// only escaped this because `migrate_config` grandfathered its already-present
/// plugin into the list.
///
/// Returns `true` if the file was changed. A `config.yaml` that exists but does
/// not parse as a YAML mapping is left untouched (returns an error) so the
/// caller can fall back to the manual `hermes plugins enable chorum` hint
/// rather than clobber a config we don't understand.
pub fn enable_plugin_in_config(config_path: &Path) -> Result<bool, Error> {
    use serde_yaml::{Mapping, Value};

    let existing = std::fs::read_to_string(config_path).unwrap_or_default();
    let mut root: Value = if existing.trim().is_empty() {
        Value::Mapping(Mapping::new())
    } else {
        serde_yaml::from_str(&existing)?
    };

    let map = root
        .as_mapping_mut()
        .ok_or("config.yaml is not a YAML mapping")?;
    let plugins = map
        .entry(Value::from("plugins"))
        .or_insert_with(|| Value::Mapping(Mapping::new()))
        .as_mapping_mut()
        .ok_or("config.yaml `plugins` is not a mapping")?;

    let added = list_add_sorted(plugins, "enabled", PLUGIN_DIRNAME);
    let removed = list_discard(plugins, "disabled", PLUGIN_DIRNAME);
    if !added && !removed {
        return Ok(false);
    }

    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(config_path, serde_yaml::to_string(&root)?)?;
    Ok(true)
}

/// Ensure `key`'s sequence under `m` contains `value`, kept sorted + deduped to
/// match Hermes' own `sorted(set(...))` write. Returns `true` if it was added.
/// A non-sequence value under `key` is left alone (we don't clobber it).
fn list_add_sorted(m: &mut serde_yaml::Mapping, key: &str, value: &str) -> bool {
    use serde_yaml::Value;
    let items = match m
        .entry(Value::from(key))
        .or_insert_with(|| Value::Sequence(Vec::new()))
        .as_sequence_mut()
    {
        Some(s) => s,
        None => return false,
    };
    if items.iter().any(|v| v.as_str() == Some(value)) {
        return false;
    }
    items.push(Value::from(value));
    items.sort_by(|a, b| a.as_str().unwrap_or("").cmp(b.as_str().unwrap_or("")));
    true
}

/// Remove `value` from `key`'s sequence under `m` if present. Returns `true` if
/// something was removed.
fn list_discard(m: &mut serde_yaml::Mapping, key: &str, value: &str) -> bool {
    let Some(seq) = m.get_mut(key).and_then(|v| v.as_sequence_mut()) else {
        return false;
    };
    let before = seq.len();
    seq.retain(|v| v.as_str() != Some(value));
    seq.len() != before
}

/// Idempotent upsert of `KEY=value` lines in an env file. Preserves comments,
/// blank lines, and unrelated keys. `updates` order is preserved on append.
pub fn upsert_env(updates: &[(String, String)], env_path: &Path) -> Result<(), Error> {
    if let Some(parent) = env_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let existing = std::fs::read_to_string(env_path).unwrap_or_default();
    let mut remaining: Vec<(String, String)> = updates.to_vec();
    let mut out: Vec<String> = Vec::new();

    for line in existing.lines() {
        let stripped = line.trim_start();
        if stripped.starts_with('#') || !stripped.contains('=') {
            out.push(line.to_string());
            continue;
        }
        let mut head = stripped;
        if let Some(rest) = head.strip_prefix("export ") {
            head = rest.trim_start();
        }
        let key = head.split('=').next().unwrap_or("").trim();
        if let Some(pos) = remaining.iter().position(|(k, _)| k == key) {
            let (k, v) = remaining.remove(pos);
            out.push(format!("{k}={v}"));
        } else {
            out.push(line.to_string());
        }
    }
    for (k, v) in remaining {
        out.push(format!("{k}={v}"));
    }
    let body = if out.is_empty() {
        String::new()
    } else {
        format!("{}\n", out.join("\n"))
    };
    std::fs::write(env_path, body)?;
    Ok(())
}

/// Persist any explicitly-provided (non-default) URLs to `env_path`. Returns the
/// keys written, or `None` if nothing was non-default.
pub fn persist_broker_urls(
    broker_url: Option<&str>,
    bridge_url: Option<&str>,
    broker_default: &str,
    bridge_default: &str,
    env_path: &Path,
) -> Result<Option<Vec<String>>, Error> {
    let mut updates: Vec<(String, String)> = Vec::new();
    if let Some(url) = broker_url {
        if url != broker_default {
            updates.push(("CHORUM_SKILL_BROKER_URL".to_string(), url.to_string()));
        }
    }
    if let Some(url) = bridge_url {
        if url != bridge_default {
            updates.push(("CHORUM_SKILL_SELF_BRIDGE_URL".to_string(), url.to_string()));
        }
    }
    if updates.is_empty() {
        return Ok(None);
    }
    let keys: Vec<String> = updates.iter().map(|(k, _)| k.clone()).collect();
    upsert_env(&updates, env_path)?;
    Ok(Some(keys))
}

/// The systemd `--user` gateway service for the active Hermes home. The default
/// profile uses the legacy `hermes-gateway`; a named profile under
/// `~/.hermes/profiles/<name>` uses `hermes-gateway-<name>`. Returns `None` for a
/// custom home off the standard layout, where the service name is unknowable.
pub fn gateway_service() -> Option<String> {
    service_for_home(&hermes_home(), &default_hermes_root())
}

fn service_for_home(home: &Path, default_root: &Path) -> Option<String> {
    if home == default_root {
        return Some("hermes-gateway".to_string());
    }
    if let Ok(rest) = home.strip_prefix(default_root.join("profiles")) {
        let mut comps = rest.components();
        if let (Some(std::path::Component::Normal(name)), None) = (comps.next(), comps.next()) {
            if let Some(name) = name.to_str() {
                return Some(format!("hermes-gateway-{name}"));
            }
        }
    }
    None
}

/// Shell command to restart the active profile's gateway, for manual-fallback hints.
pub fn gateway_restart_hint() -> String {
    match gateway_service() {
        Some(svc) => format!("systemctl --user restart {svc}"),
        None => "systemctl --user restart <your-hermes-gateway-service>".to_string(),
    }
}

/// Best-effort `systemctl --user restart <gateway service>` for the active
/// profile. Returns (ok, message).
pub fn restart_gateway() -> (bool, String) {
    let service = match gateway_service() {
        Some(s) => s,
        None => {
            return (
                false,
                "could not determine the gateway service for this Hermes home".to_string(),
            )
        }
    };
    match Command::new("systemctl")
        .args(["--user", "restart", &service])
        .output()
    {
        Ok(out) if out.status.success() => (true, format!("restarted {service}")),
        Ok(out) => {
            let detail = String::from_utf8_lossy(&out.stderr);
            let detail = detail.trim();
            let detail = if detail.is_empty() {
                format!("exit {}", out.status.code().unwrap_or(-1))
            } else {
                detail.to_string()
            };
            (false, format!("systemctl restart failed: {detail}"))
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => (
            false,
            "systemctl not found (not a systemd host?)".to_string(),
        ),
        Err(e) => (false, format!("systemctl restart failed: {e}")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shim_is_binary_mode_and_drives_cli() {
        let shim = build_subprocess_shim("/opt/chorum/bin/chorum-skill", None);
        assert!(shim.contains("CHORUM_BIN = \"/opt/chorum/bin/chorum-skill\""));
        assert!(!shim.contains("import chorum_skill"));
        assert!(!shim.contains("from chorum_skill"));
        assert!(shim.contains("list-questions"));
        assert!(shim.contains("submit-answer"));
        assert!(shim.contains("submit-no-signal"));
        assert!(shim.contains("chorum_submit_no_signal"));
        assert!(shim.contains("def register(ctx):"));
    }

    #[test]
    fn shim_parks_cron_when_budget_reached() {
        // The generated shim must react to the binary's budget_reached flag by
        // swapping the cron onto the once-a-month suspend schedule, and restore
        // the daily cadence otherwise — all via update_job(schedule=...).
        let shim = build_subprocess_shim("/opt/chorum/bin/chorum-skill", None);
        assert!(shim.contains("BUDGET_SUSPEND_SCHEDULE = \"0 9 1 * *\""));
        assert!(shim.contains("def _apply_budget_schedule(raw):"));
        assert!(shim.contains("_apply_budget_schedule(out)"));
        assert!(shim.contains("data.get(\"budget_reached\")"));
        assert!(shim.contains("update_job(job[\"id\"], {\"schedule\": BUDGET_SUSPEND_SCHEDULE})"));
        assert!(shim.contains("update_job(job[\"id\"], {\"schedule\": DEFAULT_SCHEDULE})"));
    }

    #[test]
    fn shim_grants_recall_toolsets_to_cron() {
        // The answering cron must reach the agent's own recall tools, not just
        // chorum's submit tools — otherwise it answers blind. The baked
        // ANSWER_TOOLSETS list must include session_search (past-conversation
        // RAG) and memory, and the cron must be created with that list.
        let shim = build_subprocess_shim("/opt/chorum/bin/chorum-skill", None);
        assert!(shim.contains("ANSWER_TOOLSETS = [\"chorum\", \"session_search\", \"memory\"]"));
        assert!(shim.contains("enabled_toolsets=list(ANSWER_TOOLSETS)"));
        // The prompt must actively drive retrieval, not just hint at "memory".
        assert!(shim.contains("session_search"));
    }

    #[test]
    fn shim_resolves_root_from_hermes_home() {
        // The in-gateway shim must look under $HERMES_HOME so the cron self-check
        // finds the delegation token in the active profile, not the default one.
        let shim = build_subprocess_shim("/opt/chorum/bin/chorum-skill", None);
        assert!(shim.contains("os.environ.get(\"HERMES_HOME\")"));
        assert!(shim.contains("def _chorum_root():"));
    }

    #[test]
    fn shim_pins_installed_root_into_subprocess_env() {
        // A baked root must be passed to the binary as CHORUM_SKILL_ROOT_DIR so a
        // cron/sandbox subprocess that drops HERMES_HOME still reads the right
        // profile's delegation token + ledger (the global-fallback bug).
        let shim = build_subprocess_shim(
            "/opt/chorum/bin/chorum-skill",
            Some("/home/u/.hermes/profiles/anita/chorum"),
        );
        assert!(shim.contains("CHORUM_ROOT = \"/home/u/.hermes/profiles/anita/chorum\""));
        assert!(shim.contains("def _skill_env():"));
        assert!(shim.contains("env=_skill_env()"));
        assert!(shim.contains("env[\"CHORUM_SKILL_ROOT_DIR\"] = CHORUM_ROOT"));
    }

    #[test]
    fn shim_without_root_bakes_empty_and_keeps_runtime_fallback() {
        // Off-standard layout (None) → empty constant, runtime resolution intact.
        let shim = build_subprocess_shim("/opt/chorum/bin/chorum-skill", None);
        assert!(shim.contains("CHORUM_ROOT = \"\""));
        assert!(shim.contains("os.environ.get(\"HERMES_HOME\")"));
    }

    #[test]
    fn install_plugin_dir_bakes_profile_root_from_target() {
        // The shim's baked root is the sibling `chorum` dir of the plugins tree
        // it's written into, so it tracks whichever profile owns the plugin.
        let dir = tempfile::tempdir().unwrap();
        let plugin_target = dir
            .path()
            .join("profiles")
            .join("anita")
            .join("plugins")
            .join("chorum");
        install_plugin_dir(Some(&plugin_target), Some("/opt/chorum/bin/chorum-skill")).unwrap();
        let shim = std::fs::read_to_string(plugin_target.join("__init__.py")).unwrap();
        let expected_root = dir.path().join("profiles").join("anita").join("chorum");
        assert!(shim.contains(&format!("CHORUM_ROOT = \"{}\"", expected_root.display())));
    }

    #[test]
    fn profiles_in_lists_sorted_dirs() {
        let dir = tempfile::tempdir().unwrap();
        let profiles = dir.path().join("profiles");
        std::fs::create_dir_all(profiles.join("coder")).unwrap();
        std::fs::create_dir_all(profiles.join("assistant")).unwrap();
        // A stray file under profiles/ must be ignored (only dirs are profiles).
        std::fs::write(profiles.join("notes.txt"), "x").unwrap();
        assert_eq!(profiles_in(dir.path()), vec!["assistant", "coder"]);
    }

    #[test]
    fn profiles_in_empty_when_absent() {
        let dir = tempfile::tempdir().unwrap();
        assert!(profiles_in(dir.path()).is_empty());
    }

    #[test]
    fn gateway_service_maps_home_to_unit() {
        let root = PathBuf::from("/home/u/.hermes");
        assert_eq!(
            service_for_home(&root, &root),
            Some("hermes-gateway".into())
        );
        assert_eq!(
            service_for_home(&root.join("profiles").join("coder"), &root),
            Some("hermes-gateway-coder".into())
        );
        // Nested deeper than a single profile name → not a recognizable profile.
        assert_eq!(
            service_for_home(&root.join("profiles").join("coder").join("sub"), &root),
            None
        );
        // A custom home off the standard layout → unknown service.
        assert_eq!(service_for_home(&PathBuf::from("/opt/agent"), &root), None);
    }

    fn enabled_set(config_path: &Path) -> Vec<String> {
        let v: serde_yaml::Value =
            serde_yaml::from_str(&std::fs::read_to_string(config_path).unwrap()).unwrap();
        v["plugins"]["enabled"]
            .as_sequence()
            .unwrap()
            .iter()
            .map(|s| s.as_str().unwrap().to_string())
            .collect()
    }

    #[test]
    fn enable_plugin_creates_allow_list_when_config_absent() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path().join("config.yaml");
        assert!(enable_plugin_in_config(&cfg).unwrap());
        assert_eq!(enabled_set(&cfg), vec!["chorum"]);
        // Second call is a no-op (already enabled).
        assert!(!enable_plugin_in_config(&cfg).unwrap());
    }

    #[test]
    fn enable_plugin_preserves_other_keys_and_plugins_sorted() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path().join("config.yaml");
        std::fs::write(&cfg, "model: claude\nplugins:\n  enabled:\n  - zzz-other\n").unwrap();
        assert!(enable_plugin_in_config(&cfg).unwrap());
        // chorum is added, the pre-existing plugin is kept, and the list is sorted.
        assert_eq!(enabled_set(&cfg), vec!["chorum", "zzz-other"]);
        // Unrelated top-level keys survive the round-trip.
        let v: serde_yaml::Value =
            serde_yaml::from_str(&std::fs::read_to_string(&cfg).unwrap()).unwrap();
        assert_eq!(v["model"].as_str(), Some("claude"));
    }

    #[test]
    fn enable_plugin_clears_stale_disabled_entry() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path().join("config.yaml");
        std::fs::write(&cfg, "plugins:\n  disabled:\n  - chorum\n").unwrap();
        assert!(enable_plugin_in_config(&cfg).unwrap());
        assert_eq!(enabled_set(&cfg), vec!["chorum"]);
        let v: serde_yaml::Value =
            serde_yaml::from_str(&std::fs::read_to_string(&cfg).unwrap()).unwrap();
        // A deny-list entry would override the allow-list, so it must be gone.
        assert!(v["plugins"]["disabled"].as_sequence().unwrap().is_empty());
    }

    #[test]
    fn enable_plugin_refuses_to_clobber_unparseable_config() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path().join("config.yaml");
        // A YAML scalar is valid YAML but not a mapping — leave it untouched.
        std::fs::write(&cfg, "just-a-string\n").unwrap();
        assert!(enable_plugin_in_config(&cfg).is_err());
        assert_eq!(std::fs::read_to_string(&cfg).unwrap(), "just-a-string\n");
    }

    #[test]
    fn env_upsert_replaces_and_appends() {
        let dir = tempfile::tempdir().unwrap();
        let env = dir.path().join(".env");
        std::fs::write(&env, "# comment\nCHORUM_SKILL_BROKER_URL=old\nOTHER=keep\n").unwrap();
        upsert_env(
            &[
                ("CHORUM_SKILL_BROKER_URL".into(), "https://new".into()),
                (
                    "CHORUM_SKILL_SELF_BRIDGE_URL".into(),
                    "https://bridge".into(),
                ),
            ],
            &env,
        )
        .unwrap();
        let out = std::fs::read_to_string(&env).unwrap();
        assert_eq!(
            out,
            "# comment\nCHORUM_SKILL_BROKER_URL=https://new\nOTHER=keep\nCHORUM_SKILL_SELF_BRIDGE_URL=https://bridge\n"
        );
    }
}
