//! Hermes host adapter — directory plugin install + subprocess shim.
//!
//! Hermes' built-in installers don't fit our shape, so we use the deterministic
//! path: drop a 2-file directory under `~/.hermes/plugins/hearme/` (manifest +
//! a stdlib-only Python shim that shells out to this binary), then restart the
//! gateway. Because the gateway runs Python but has no `hearme_skill` package
//! installed (binary mode), the shim re-implements the two-tool contract by
//! invoking the binary's CLI subcommands.

use std::path::{Path, PathBuf};
use std::process::Command;

use crate::contracts::{
    py_str, ANSWER_PROMPT, DEFAULT_SCHEDULE, JOB_NAME, LIST_SCHEMA_PY, SUBMIT_SCHEMA_PY, TOOLSET,
};
use crate::Error;

const PLUGIN_DIRNAME: &str = "hearme";

/// Embedded Hermes manifest. Kept in step with packages/skill/plugin.yaml.
pub const PLUGIN_MANIFEST: &str = "name: hearme\nversion: 0.0.1\ndescription: >-\n  Answer public yes/no questions on the user's behalf, using the host agent's\n  own model and memory. Inference needs no extra API key; a cron job drives the\n  answering cycle.\nauthor: Hearme\nkind: standalone\nprovides_tools:\n  - hearme_list_open_questions\n  - hearme_submit_answer\n";

fn hermes_home() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".hermes")
}

pub fn plugin_dir() -> PathBuf {
    hermes_home().join("plugins").join(PLUGIN_DIRNAME)
}

pub fn hermes_env_path() -> PathBuf {
    hermes_home().join(".env")
}

/// Build the self-contained Hermes plugin shim that shells out to `binary_path`.
/// The source imports only the stdlib (the `cron` import is lazy), so it loads
/// inside a gateway with no `hearme_skill` package.
pub fn build_subprocess_shim(binary_path: &str) -> String {
    const TEMPLATE: &str = r##""""Auto-generated Hearme plugin shim (binary mode).

Generated by `hearme-skill install` / `install-plugin` running as the
standalone `hearme-skill` binary. The Hermes gateway loads this module; it
needs NO pip-installed hearme_skill package — every operation shells out to
the binary below. Do not edit by hand; re-run the installer to regenerate.
"""

import json
import logging
import os
import subprocess
from pathlib import Path

log = logging.getLogger("hearme_skill.shim")

HEARME_BIN = @@HEARME_BIN@@
TOOLSET = @@TOOLSET@@
JOB_NAME = @@JOB_NAME@@
DEFAULT_SCHEDULE = @@DEFAULT_SCHEDULE@@
ANSWER_PROMPT = @@ANSWER_PROMPT@@
_LIST_SCHEMA = @@LIST_SCHEMA@@
_SUBMIT_SCHEMA = @@SUBMIT_SCHEMA@@


def _run(args):
    try:
        proc = subprocess.run(
            [HEARME_BIN, *args], capture_output=True, text=True, timeout=180
        )
    except Exception as exc:  # noqa: BLE001
        return json.dumps({"error": "hearme binary failed: " + str(exc)})
    out = (proc.stdout or "").strip()
    if out:
        return out
    return json.dumps({"error": (proc.stderr or "no output from hearme binary").strip()})


def _handle_list(args, **_kwargs):
    return _run(["list-questions"])


def _handle_submit(args, **_kwargs):
    a = args or {}
    question_id = str(a.get("question_id") or "").strip()
    answer = str(a.get("answer") or "").strip()
    if not question_id or not answer:
        return json.dumps({"accepted": False, "reason": "question_id and answer are required"})
    return _run(["submit-answer", "--question-id", question_id, "--answer", answer])


def _delegation_exists():
    root = os.environ.get("HEARME_SKILL_ROOT_DIR") or str(Path.home() / ".hermes" / "hearme")
    return (Path(root) / "delegation.token").exists()


def _ensure_cron():
    # The shim runs inside the Hermes gateway, so the `cron` package is importable here.
    if not _delegation_exists():
        return
    try:
        from cron.jobs import create_job, resolve_job_ref
    except Exception:  # noqa: BLE001
        return
    try:
        if resolve_job_ref(JOB_NAME):
            return
        create_job(
            prompt=ANSWER_PROMPT,
            schedule=DEFAULT_SCHEDULE,
            name=JOB_NAME,
            enabled_toolsets=[TOOLSET],
        )
    except Exception:  # noqa: BLE001
        log.debug("Hearme cron auto-registration skipped", exc_info=True)


def register(ctx):
    ctx.register_tool(
        name="hearme_list_open_questions",
        toolset=TOOLSET,
        schema=_LIST_SCHEMA,
        handler=_handle_list,
        description="List open Hearme questions the policy permits answering.",
        emoji="\U0001f5f3️",
    )
    ctx.register_tool(
        name="hearme_submit_answer",
        toolset=TOOLSET,
        schema=_SUBMIT_SCHEMA,
        handler=_handle_submit,
        description="Sign + submit one Hearme answer on the user's behalf.",
        emoji="\U0001f5f3️",
    )
    _ensure_cron()
"##;

    TEMPLATE
        .replace("@@HEARME_BIN@@", &py_str(binary_path))
        .replace("@@TOOLSET@@", &py_str(TOOLSET))
        .replace("@@JOB_NAME@@", &py_str(JOB_NAME))
        .replace("@@DEFAULT_SCHEDULE@@", &py_str(DEFAULT_SCHEDULE))
        .replace("@@ANSWER_PROMPT@@", &py_str(ANSWER_PROMPT))
        .replace("@@LIST_SCHEMA@@", LIST_SCHEMA_PY)
        .replace("@@SUBMIT_SCHEMA@@", SUBMIT_SCHEMA_PY)
}

/// Write the Hermes directory-install drop-in (manifest + shim). Idempotent;
/// always overwrites both files. `binary_path` defaults to the current
/// executable. Returns the directory written.
pub fn install_plugin_dir(
    plugin_dir_override: Option<&Path>,
    binary_path: Option<&str>,
) -> Result<PathBuf, Error> {
    let target = plugin_dir_override
        .map(|p| p.to_path_buf())
        .unwrap_or_else(plugin_dir);
    std::fs::create_dir_all(&target)?;
    std::fs::write(target.join("plugin.yaml"), PLUGIN_MANIFEST)?;

    let resolved_bin = match binary_path {
        Some(b) => b.to_string(),
        None => std::env::current_exe()?.to_string_lossy().into_owned(),
    };
    std::fs::write(
        target.join("__init__.py"),
        build_subprocess_shim(&resolved_bin),
    )?;
    Ok(target)
}

/// Idempotent upsert of `KEY=value` lines in an env file. Preserves comments,
/// blank lines, and unrelated keys. `updates` order is preserved on append.
pub fn upsert_env(updates: &[(String, String)], env_path: &Path) -> Result<(), Error> {
    if let Some(parent) = env_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let existing = std::fs::read_to_string(env_path).unwrap_or_default();
    let mut remaining: Vec<(String, String)> = updates.to_vec();
    let mut out: Vec<String> = Vec::new();

    for line in existing.lines() {
        let stripped = line.trim_start();
        if stripped.starts_with('#') || !stripped.contains('=') {
            out.push(line.to_string());
            continue;
        }
        let mut head = stripped;
        if let Some(rest) = head.strip_prefix("export ") {
            head = rest.trim_start();
        }
        let key = head.split('=').next().unwrap_or("").trim();
        if let Some(pos) = remaining.iter().position(|(k, _)| k == key) {
            let (k, v) = remaining.remove(pos);
            out.push(format!("{k}={v}"));
        } else {
            out.push(line.to_string());
        }
    }
    for (k, v) in remaining {
        out.push(format!("{k}={v}"));
    }
    let body = if out.is_empty() {
        String::new()
    } else {
        format!("{}\n", out.join("\n"))
    };
    std::fs::write(env_path, body)?;
    Ok(())
}

/// Persist any explicitly-provided (non-default) URLs to `env_path`. Returns the
/// keys written, or `None` if nothing was non-default.
pub fn persist_broker_urls(
    broker_url: Option<&str>,
    bridge_url: Option<&str>,
    broker_default: &str,
    bridge_default: &str,
    env_path: &Path,
) -> Result<Option<Vec<String>>, Error> {
    let mut updates: Vec<(String, String)> = Vec::new();
    if let Some(url) = broker_url {
        if url != broker_default {
            updates.push(("HEARME_SKILL_BROKER_URL".to_string(), url.to_string()));
        }
    }
    if let Some(url) = bridge_url {
        if url != bridge_default {
            updates.push(("HEARME_SKILL_SELF_BRIDGE_URL".to_string(), url.to_string()));
        }
    }
    if updates.is_empty() {
        return Ok(None);
    }
    let keys: Vec<String> = updates.iter().map(|(k, _)| k.clone()).collect();
    upsert_env(&updates, env_path)?;
    Ok(Some(keys))
}

/// Best-effort `systemctl --user restart hermes-gateway`. Returns (ok, message).
pub fn restart_gateway() -> (bool, String) {
    match Command::new("systemctl")
        .args(["--user", "restart", "hermes-gateway"])
        .output()
    {
        Ok(out) if out.status.success() => (true, "restarted hermes-gateway".to_string()),
        Ok(out) => {
            let detail = String::from_utf8_lossy(&out.stderr);
            let detail = detail.trim();
            let detail = if detail.is_empty() {
                format!("exit {}", out.status.code().unwrap_or(-1))
            } else {
                detail.to_string()
            };
            (false, format!("systemctl restart failed: {detail}"))
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => (
            false,
            "systemctl not found (not a systemd host?)".to_string(),
        ),
        Err(e) => (false, format!("systemctl restart failed: {e}")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shim_is_binary_mode_and_drives_cli() {
        let shim = build_subprocess_shim("/opt/hearme/bin/hearme-skill");
        assert!(shim.contains("HEARME_BIN = \"/opt/hearme/bin/hearme-skill\""));
        assert!(!shim.contains("import hearme_skill"));
        assert!(!shim.contains("from hearme_skill"));
        assert!(shim.contains("list-questions"));
        assert!(shim.contains("submit-answer"));
        assert!(shim.contains("def register(ctx):"));
    }

    #[test]
    fn env_upsert_replaces_and_appends() {
        let dir = tempfile::tempdir().unwrap();
        let env = dir.path().join(".env");
        std::fs::write(&env, "# comment\nHEARME_SKILL_BROKER_URL=old\nOTHER=keep\n").unwrap();
        upsert_env(
            &[
                ("HEARME_SKILL_BROKER_URL".into(), "https://new".into()),
                (
                    "HEARME_SKILL_SELF_BRIDGE_URL".into(),
                    "https://bridge".into(),
                ),
            ],
            &env,
        )
        .unwrap();
        let out = std::fs::read_to_string(&env).unwrap();
        assert_eq!(
            out,
            "# comment\nHEARME_SKILL_BROKER_URL=https://new\nOTHER=keep\nHEARME_SKILL_SELF_BRIDGE_URL=https://bridge\n"
        );
    }
}
