"""Hermes plugin shim generation.

The Hermes gateway loads a directory plugin from ``~/.hermes/plugins/hearme/``
and calls ``register(ctx)``. There are two ways to wire that up:

* **Import shim** (:data:`IMPORT_SHIM`) — a one-liner that re-exports
  ``register`` from the pip-installed ``hearme_skill`` package. Used when the
  user ``pip install``\\ed the package into the gateway venv.

* **Subprocess shim** (:func:`build_subprocess_shim`) — a self-contained module
  (stdlib only) whose two tool handlers shell out to the standalone
  ``hearme-skill`` binary. Used in *binary mode*: the user downloaded the
  prebuilt binary (no Python install), so the gateway has no ``hearme_skill``
  package to import — all logic lives in the binary. This keeps a single source
  of truth (the binary) while letting Hermes register the same two typed tools
  it always has.

Both shims register the identical tools (``hearme_list_open_questions`` /
``hearme_submit_answer``) with the identical schemas — the subprocess shim
copies the schemas + cron contract out of :mod:`hearme_skill.plugin` /
:mod:`hearme_skill.schedule` at generation time, so they cannot drift.
"""

from __future__ import annotations

# Used when hearme_skill is pip-installed in the gateway venv.
IMPORT_SHIM = "from hearme_skill.plugin import register  # noqa: F401\n"


def build_subprocess_shim(binary_path: str) -> str:
    """Return a self-contained Hermes plugin shim that shells out to ``binary_path``.

    The returned source imports only the stdlib and the gateway-provided ``cron``
    package, so it runs inside a Hermes gateway that has **no** ``hearme_skill``
    package installed. Schemas, toolset name, and the cron contract are baked in
    from the canonical modules so the binary and the shim stay in lockstep.
    """

    # Imported lazily (only at install time) to avoid importing the heavy answering
    # stack — and any agent framework — just to load this module.
    from .plugin import _LIST_SCHEMA, _SUBMIT_SCHEMA, TOOLSET
    from .schedule import ANSWER_PROMPT, DEFAULT_SCHEDULE, JOB_NAME

    # Each value is rendered with repr(), which yields a valid Python literal for
    # the str/list/dict-of-str structures involved (and escapes newlines in the
    # prompt). The whole result is compile()-checked by tests/test_binary_packaging.
    lines = [
        '"""Auto-generated Hearme plugin shim (binary mode).',
        "",
        "Generated by `hearme-skill install` / `install-plugin` running as the",
        "standalone `hearme-skill` binary. The Hermes gateway loads this module; it",
        "needs NO pip-installed hearme_skill package — every operation shells out to",
        "the binary below. Do not edit by hand; re-run the installer to regenerate.",
        '"""',
        "",
        "import json",
        "import logging",
        "import os",
        "import subprocess",
        "from pathlib import Path",
        "",
        'log = logging.getLogger("hearme_skill.shim")',
        "",
        f"HEARME_BIN = {binary_path!r}",
        f"TOOLSET = {TOOLSET!r}",
        f"JOB_NAME = {JOB_NAME!r}",
        f"DEFAULT_SCHEDULE = {DEFAULT_SCHEDULE!r}",
        f"ANSWER_PROMPT = {ANSWER_PROMPT!r}",
        f"_LIST_SCHEMA = {_LIST_SCHEMA!r}",
        f"_SUBMIT_SCHEMA = {_SUBMIT_SCHEMA!r}",
        "",
        "",
        "def _run(args):",
        "    try:",
        "        proc = subprocess.run(",
        "            [HEARME_BIN, *args], capture_output=True, text=True, timeout=180",
        "        )",
        "    except Exception as exc:  # noqa: BLE001",
        '        return json.dumps({"error": "hearme binary failed: " + str(exc)})',
        '    out = (proc.stdout or "").strip()',
        "    if out:",
        "        return out",
        '    return json.dumps({"error": (proc.stderr or "no output from hearme binary").strip()})',
        "",
        "",
        "def _handle_list(args, **_kwargs):",
        '    return _run(["list-questions"])',
        "",
        "",
        "def _handle_submit(args, **_kwargs):",
        "    a = args or {}",
        '    question_id = str(a.get("question_id") or "").strip()',
        '    answer = str(a.get("answer") or "").strip()',
        "    if not question_id or not answer:",
        '        return json.dumps({"accepted": False, "reason": "question_id and answer are required"})',
        '    return _run(["submit-answer", "--question-id", question_id, "--answer", answer])',
        "",
        "",
        "def _delegation_exists():",
        '    root = os.environ.get("HEARME_SKILL_ROOT_DIR") or str(Path.home() / ".hermes" / "hearme")',
        '    return (Path(root) / "delegation.token").exists()',
        "",
        "",
        "def _ensure_cron():",
        "    # The shim runs inside the Hermes gateway, so the `cron` package is importable here.",
        "    if not _delegation_exists():",
        "        return",
        "    try:",
        "        from cron.jobs import create_job, resolve_job_ref",
        "    except Exception:  # noqa: BLE001",
        "        return",
        "    try:",
        "        if resolve_job_ref(JOB_NAME):",
        "            return",
        "        create_job(",
        "            prompt=ANSWER_PROMPT,",
        "            schedule=DEFAULT_SCHEDULE,",
        "            name=JOB_NAME,",
        "            enabled_toolsets=[TOOLSET],",
        "        )",
        "    except Exception:  # noqa: BLE001",
        '        log.debug("Hearme cron auto-registration skipped", exc_info=True)',
        "",
        "",
        "def register(ctx):",
        "    ctx.register_tool(",
        '        name="hearme_list_open_questions",',
        "        toolset=TOOLSET,",
        "        schema=_LIST_SCHEMA,",
        "        handler=_handle_list,",
        '        description="List open Hearme questions the policy permits answering.",',
        '        emoji="\\U0001f5f3\\ufe0f",',
        "    )",
        "    ctx.register_tool(",
        '        name="hearme_submit_answer",',
        "        toolset=TOOLSET,",
        "        schema=_SUBMIT_SCHEMA,",
        "        handler=_handle_submit,",
        "        description=\"Sign + submit one Hearme answer on the user's behalf.\",",
        '        emoji="\\U0001f5f3\\ufe0f",',
        "    )",
        "    _ensure_cron()",
        "",
    ]
    return "\n".join(lines)
