# @generated by packages/web/scripts/codegen.mjs from
# packages/web/drizzle/schema.sql. DO NOT EDIT. Run `npm run db:codegen`.

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class AggregatesRow(BaseModel):
    """Row of the `aggregates` table."""

    model_config = ConfigDict(extra="forbid")

    question_id: UUID
    total_answers: int
    by_predicate: Any
    updated_at: datetime


class AskersRow(BaseModel):
    """Row of the `askers` table."""

    model_config = ConfigDict(extra="forbid")

    id: UUID
    display_name: str
    created_at: datetime


class EnvelopesRow(BaseModel):
    """Row of the `envelopes` table."""

    model_config = ConfigDict(extra="forbid")

    question_id: UUID
    unique_identifier: str
    answer: str
    disclosed_predicates: Any
    agent_signature: str
    delegation_hash: str
    submitted_at: datetime


class QuestionsRow(BaseModel):
    """Row of the `questions` table."""

    model_config = ConfigDict(extra="forbid")

    id: UUID
    asker_id: UUID | None = None
    text: str
    topic: str | None = None
    nonce: str
    created_at: datetime
    closes_at: datetime
    status: str
    options: Any
    scope: str
    country: str | None = None
    continent: str | None = None


class RegistrationsRow(BaseModel):
    """Row of the `registrations` table."""

    model_config = ConfigDict(extra="forbid")

    unique_identifier: str
    agent_key: str
    disclosed_predicates: Any
    issued_at: datetime
    expires_at: datetime
    revoked_at: datetime | None = None


class RevocationsRow(BaseModel):
    """Row of the `revocations` table."""

    model_config = ConfigDict(extra="forbid")

    delegation_hash: str
    revoked_at: datetime


class SelfChainCursorsRow(BaseModel):
    """Row of the `self_chain_cursors` table."""

    model_config = ConfigDict(extra="forbid")

    name: str
    last_block: int
    updated_at: datetime


class SelfNullifierInvalidationsRow(BaseModel):
    """Row of the `self_nullifier_invalidations` table."""

    model_config = ConfigDict(extra="forbid")

    unique_identifier: str
    source: str
    chain_id: str | None = None
    block_number: int
    log_index: int
    tx_hash: str
    observed_at: datetime
