#!/usr/bin/env node
// Code generation for the SQL-as-source schema.
//
// packages/web/drizzle/schema.sql is the single source of truth. From it we
// generate, never hand-edit:
//   - packages/web/src/db/schema.ts                     (Drizzle TS, for web)
//   - packages/broker/.../db/rows_generated.py          (Pydantic row models)
//
// How: apply schema.sql to a throwaway database, then
//   - TS:  `drizzle-kit pull` introspects it into a Drizzle schema, which we
//          post-process (see PATCHES) to fix two drizzle-kit-pull limitations —
//          it emits SQL-function defaults as bare calls (invalid TS) and drops
//          column type refinements (jsonb -> unknown).
//   - Py:  introspect information_schema here and render Pydantic models.
//
// Usage:
//   node scripts/codegen.mjs            # write the generated files in place
//   node scripts/codegen.mjs --check    # generate to temp, diff vs committed,
//                                        # exit 1 on drift (CI)
//
// Env: ADMIN_DATABASE_URL — admin DSN with CREATEDB (default local dev creds).

import { readFileSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import postgres from "postgres";

const __dirname = dirname(fileURLToPath(import.meta.url));
const WEB_DIR = join(__dirname, "..");
const REPO_ROOT = join(WEB_DIR, "..", "..");
const SCHEMA_SQL = join(WEB_DIR, "drizzle", "schema.sql");
const TS_OUT = join(WEB_DIR, "src", "db", "schema.ts");
const PY_OUT = join(
  REPO_ROOT,
  "packages",
  "broker",
  "src",
  "hearme_broker",
  "db",
  "rows_generated.py",
);

const ADMIN_DSN =
  process.env.ADMIN_DATABASE_URL ??
  "postgres://hearme_admin:hearme_admin_dev@localhost:5432/hearme";
const BUILD_DB = "hearme_codegen_build";
const CHECK = process.argv.includes("--check");

const GEN_BANNER_TS = `// @generated by scripts/codegen.mjs from packages/web/drizzle/schema.sql.
// DO NOT EDIT. Run \`npm run db:codegen\` after changing schema.sql.
`;
const GEN_BANNER_PY = `# @generated by packages/web/scripts/codegen.mjs from
# packages/web/drizzle/schema.sql. DO NOT EDIT. Run \`npm run db:codegen\`.
`;

// Post-processing the drizzle-kit pull output. Each patch documents a concrete
// drizzle-kit-pull limitation it works around. This list is, in effect, schema
// knowledge that schema.sql alone can't convey to the TS layer.
const PATCHES = [
  {
    why: "pull emits the SQL-function default as a bare, backslash-escaped call (invalid TS); wrap in sql``",
    find: ".default(encode(gen_random_bytes(16), \\'base64\\'::text))",
    repl: ".default(sql`encode(gen_random_bytes(16), 'base64')`)",
  },
  {
    why: "pull types jsonb as unknown; re-apply the string[] refinement the web app relies on",
    find: "options: jsonb().default(",
    repl: "options: jsonb().$type<string[]>().default(",
  },
  {
    why: "pull pins timestamps to mode:'string'; the app passes/compares Date (drizzle's default mode:'date')",
    find: "{ withTimezone: true, mode: 'string' }",
    repl: "{ withTimezone: true }",
  },
];

function dsnFor(db) {
  const u = new URL(ADMIN_DSN);
  u.pathname = `/${db}`;
  return u.toString();
}

async function buildSchemaDb(admin) {
  await admin.unsafe(`DROP DATABASE IF EXISTS ${BUILD_DB} WITH (FORCE)`);
  await admin.unsafe(`CREATE DATABASE ${BUILD_DB}`);
  const sql = postgres(dsnFor(BUILD_DB), { max: 1, onnotice: () => {} });
  try {
    await sql.unsafe(readFileSync(SCHEMA_SQL, "utf8"));
  } finally {
    await sql.end({ timeout: 5 });
  }
}

function generateTs(tmp) {
  const res = spawnSync(
    join(WEB_DIR, "node_modules", ".bin", "drizzle-kit"),
    ["pull", "--out", tmp, "--dialect", "postgresql", "--url", dsnFor(BUILD_DB)],
    { cwd: WEB_DIR, encoding: "utf8" },
  );
  if (res.status !== 0) {
    console.error(res.stdout, res.stderr);
    throw new Error("drizzle-kit pull failed");
  }
  let ts = readFileSync(join(tmp, "schema.ts"), "utf8");
  for (const { find, repl, why } of PATCHES) {
    if (!ts.includes(find)) {
      throw new Error(
        `codegen patch no longer matches (drizzle-kit output changed?): ${why}\n  expected to find: ${find}`,
      );
    }
    ts = ts.split(find).join(repl);
  }
  return GEN_BANNER_TS + "\n" + ts.trimStart();
}

// ---- Python row models -------------------------------------------------

const PG_TO_PY = {
  uuid: "UUID",
  text: "str",
  int4: "int",
  integer: "int",
  int8: "int",
  bigint: "int",
  bool: "bool",
  boolean: "bool",
  timestamptz: "datetime",
  jsonb: "Any",
  json: "Any",
};

function pyType(udt, nullable) {
  const base = PG_TO_PY[udt] ?? "Any";
  return nullable ? `${base} | None` : base;
}

function toClassName(table) {
  return (
    table
      .split("_")
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join("") + "Row"
  );
}

async function generatePy() {
  const sql = postgres(dsnFor(BUILD_DB), { max: 1, onnotice: () => {} });
  let cols;
  try {
    cols = await sql`
      SELECT table_name, column_name, udt_name, is_nullable
      FROM information_schema.columns
      WHERE table_schema = 'public'
      ORDER BY table_name, ordinal_position
    `;
  } finally {
    await sql.end({ timeout: 5 });
  }
  const byTable = new Map();
  for (const c of cols) {
    if (!byTable.has(c.table_name)) byTable.set(c.table_name, []);
    byTable.get(c.table_name).push(c);
  }
  const used = new Set();
  const classes = [];
  for (const [table, tcols] of [...byTable].sort()) {
    const lines = [`class ${toClassName(table)}(BaseModel):`];
    lines.push(`    """Row of the \`${table}\` table."""`);
    lines.push("");
    lines.push("    model_config = ConfigDict(extra=\"forbid\")");
    lines.push("");
    for (const c of tcols) {
      const nullable = c.is_nullable === "YES";
      const t = pyType(c.udt_name, nullable);
      for (const tok of t.split(/[^A-Za-z]+/)) used.add(tok);
      const suffix = nullable ? " = None" : "";
      lines.push(`    ${c.column_name}: ${t}${suffix}`);
    }
    classes.push(lines.join("\n"));
  }
  const imports = ["from __future__ import annotations", ""];
  const typingNeeded = used.has("Any");
  const dtNeeded = used.has("datetime");
  const uuidNeeded = used.has("UUID");
  if (dtNeeded) imports.push("from datetime import datetime");
  if (typingNeeded) imports.push("from typing import Any");
  if (uuidNeeded) imports.push("from uuid import UUID");
  imports.push("");
  imports.push("from pydantic import BaseModel, ConfigDict");
  return (
    GEN_BANNER_PY +
    "\n" +
    imports.join("\n") +
    "\n\n\n" +
    classes.join("\n\n\n") +
    "\n"
  );
}

// ---- main --------------------------------------------------------------

function reportDrift(label, expected, actual) {
  if (expected === actual) return false;
  console.error(`DRIFT: ${label} is stale — regenerate with \`npm run db:codegen\`.`);
  return true;
}

async function main() {
  const admin = postgres(ADMIN_DSN, { max: 1, onnotice: () => {} });
  const tmp = mkdtempSync(join(tmpdir(), "hearme-codegen-"));
  try {
    await buildSchemaDb(admin);
    const ts = generateTs(tmp);
    const py = await generatePy();

    if (CHECK) {
      const tsOld = readFileSync(TS_OUT, "utf8");
      const pyOld = readFileSync(PY_OUT, "utf8");
      const drift =
        reportDrift("src/db/schema.ts", tsOld, ts) |
        reportDrift("broker rows_generated.py", pyOld, py);
      if (drift) process.exit(1);
      console.log("OK: generated schema.ts + rows_generated.py are up to date.");
    } else {
      writeFileSync(TS_OUT, ts);
      writeFileSync(PY_OUT, py);
      console.log(`wrote ${TS_OUT}`);
      console.log(`wrote ${PY_OUT}`);
    }
  } finally {
    await admin.unsafe(`DROP DATABASE IF EXISTS ${BUILD_DB} WITH (FORCE)`).catch(() => {});
    await admin.end({ timeout: 5 });
    rmSync(tmp, { recursive: true, force: true });
  }
}

main().catch((err) => {
  console.error("[codegen] FAILED:", err);
  process.exit(2);
});
